# Generated by Django 5.1.6 on 2025-07-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bird",
            old_name="genus_field",
            new_name="genus",
        ),
    ]
