# Generated by Django 5.1.6 on 2025-07-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_genus_field_bird_genus"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="species",
            field=models.CharField(default="unspecified", max_length=50),
            preserve_default=False,
        ),
    ]
