# Generated by Django 5.1.6 on 2025-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_bird_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="english_name",
            field=models.CharField(default="unspecified", max_length=75),
            preserve_default=False,
        ),
    ]
