# Generated by Django 5.1.6 on 2025-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_bird_english_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="subspecies",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
