# Generated by Django 5.1.6 on 2025-07-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_bird_subspecies"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="family",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
