# Docker Compose V2 configuration
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=local # Must match the environment name used in settings/__init__.py
      # Do not set DJANGO_SETTINGS_MODULE here - allow __init__.py to handle it based on DJANGO_ENV
      - IN_DOCKER=True # Helps settings determine correct database host
    env_file:
      - ./backend/.env # Load backend-specific environment variables
    depends_on:
      - db

  db:
    image: postgres:17.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hellobirdie
      - TZ=UTC
    ports:
      - "5433:5432" # Using port 5433 on host to avoid conflicts with local PostgreSQL

volumes:
  postgres_data:
